name: CI Build Training Image
on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ci-docker-build-push.yaml'
      - 'src/**'

jobs:
  docker-build:
    # Call the shared workflow
    uses: opencloudhub/.github/.github/workflows/shared-ci-docker-build-push.yaml@main
    with:
      repo-name: "wine-classifier"
      context: "."
      dockerfile: "Dockerfile"
      target: "prod"
      push-on-pr: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
